- name: installation de mentdb 
  hosts: astl-mentdb-01
  remote_user: exoadmin
  become: yes

  tasks: 
  - name: création de user-mentdb
    user:
      name: user-mentdb
      state: present
      uid: 1500
      shell: /bin/bash 
      groups: sudo
      append: yes
      password: "{{ 'Men55tdbl30' | password_hash('sha512') }}"  

    
   
  - name: mise à jour du cache apt  et install vim
    apt:
      name: vim
      update_cache: yes
      cache_valid_time: 3600

  - name: mise à jour du cache apt  et install tmux 
    apt:
      name: tmux
      update_cache: yes
      cache_valid_time: 3600


  - name: mise à jour du cache apt  et install htop
    apt:
      name: htop
      update_cache: yes
      cache_valid_time: 3600


  - name: mise à jour du cache et install mysql
    apt:
      name : mysql-server
      update_cache : yes
      force : yes
