- name: premierPlayBookTestModuleFile
  hosts: all
  remote_user: teddy
  become: yes
#  become_user: yes

  tasks: 
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    file:
      path: /home/teddy/test.txt
      state: touch
      mode: 0755
