- name: PlayBook commun pour tout serveur linux ubuntu
  hosts: all
  remote_user: teddy
  become: yes
  tasks: 
#  - name: Check for Python
#    raw: test -e /usr/bin/python
#    changed_when: false
#    failed_when: false
#    register: check_python
#
#  - name: Install Python
#    raw: apt -y update && apt install -y python-minimal
#    when: check_python.rc != 0

  - name: mise à jour du cache et install divers logiciels 
    apt:
      update_cache : yes
      cache_valid_time : 3600
      name :
        - htop
        - tmux
        - vim
        - git
        - tree

  - name: création de user-ansible
    user:
      name: user-ansible
      state: present
      uid: 1200
      shell: /bin/bash 
      groups: sudo
      append: yes
      password: "{{ 'Ansibl30' | password_hash('sha512') }}"  

  - name: création de la paire de cle ssh pour  user-ansible
    openssh_keypair:
      path: "/home/user-ansible/.ssh/id_ed25519"
      type: ed25519
      size: 4096
      state: present
      force: no 
 


  - name: création de user-mentdb
    user:
      name: user-mentdb
      state: present
      uid: 1500
      shell: /bin/bash 
      groups: sudo
      append: yes
      password: "{{ 'Mentdb30' | password_hash('sha512') }}"  

  
  
